apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: recommendation-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tracel-web-project/Travel-gitops.git
    targetRevision: main
    path: apps/dev/recommend
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
