# user-service PodMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: user-pod-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: "5001"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: user-service
  namespaceSelector:
    matchNames:
      - default

---
# flights-service PodMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: flights-pod-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: "5003"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: flights-service
  namespaceSelector:
    matchNames:
      - default

---
# holidays-service PodMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: holidays-pod-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: "5002"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: holidays-service
  namespaceSelector:
    matchNames:
      - default

---
# recommendation-backend PodMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: recommendation-pod-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: "5005"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: recommendation-backend
  namespaceSelector:
    matchNames:
      - default

---
# travel-frontend-service PodMonitor
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: frontend-pod-monitor
  namespace: monitoring
spec:
  podMetricsEndpoints:
    - port: "80"
      path: /metrics
      interval: 30s
  selector:
    matchLabels:
      app: travel-frontend      # matches your pod label exactly
  namespaceSelector:
    matchNames:
      - default                  # namespace where frontend pods run
