apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data-holiday-db-0
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""   # Important: empty so it binds to holiday-db-pv-0
