apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/Tracel-web-project/User-service//k8s?ref=main
images:
- name: sheethalshobi/user-service
  newName: sheethalshobi/user-service
  newTag: 1bd920776271cbe22c97a7446529a7fea9d1c3f0
