apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/Tracel-web-project/User-service//k8s?ref=main
images:
- name: sheethalshobi/user-service
  newName: sheethalshobi/user-service
  newTag: d9e2bc4a3fda47004fb96fe6afebb233ad3ba6ae
